### ISSUE TITLE
I AM HAVING ISSUE 

### ISSUE THREAD

**Issue by 2deadmen** [Audacity21/react-firebase#1]
I am getting an error when i try to send an otp to a mobile number which is not registered in firebase from localhost. does it only work in production for other mobile numbers..

**Comment by akashgreninja** [comment]
Same here

**Comment by Audacity21** [comment]
> I am getting an error when i try to send an otp to a mobile number which is not registered in firebase from localhost. does it only work in production for other mobile numbers..

Make sure your firebase credentials are configured properly in the firebase.js file. Tested it out just now and it works fine for any Indian phone number.
